version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ivmproject
      POSTGRES_PASSWORD: ivmproject
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass ivmproject
    volumes:
      - redis:/data

volumes:
  db:
  redis: